class Office {
    constructor(name){
        this.name = name;
        this.inventory = []
        this.init();
    }
    showOffices(){
        console.log(this.name);
    }
    init(){
        this.inventory.push( new OfficeInventory([
            new Car({
                brand : 'Audi',
                model: 'A4',
                engine: 'V12',
                capacity: 5,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Premium',
                FuelCapacity: 14.3,
                price: 45000,
            }),
            new Car({
                brand : 'Audi',
                model: 'A6',
                engine: '',
                capacity: 4,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 46000,
            }),
            new Car({
                brand : 'Mazda',
                model: 'CX-9',
                engine: '',
                capacity: 4,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 49000,
            }),
            new Car({
                brand : 'Mazda',
                model: 'CX-30',
                engine: '',
                capacity: 4,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 24000,
            }),
            new Car({
                brand : 'Mazda',
                model: 'Mazda 2',
                engine: '',
                capacity: 4,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 16000,
            }),
            new Car({
                brand : 'Mazda',
                model: 'Mazda 3',
                engine: '',
                capacity: 4,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 22000,
            }),
            new Car({
                brand : 'Nissa',
                model: 'Sentra',
                engine: '',
                capacity: 4,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Car({
                brand : 'Nissa',
                model: 'Versa',
                engine: '',
                capacity: 4,
                warranty: 5,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Honda',
                model: 'CB-190R',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Honda',
                model: 'CB-125F',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Honda',
                model: 'X-Blade',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Yamaha',
                model: 'MT03',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Yamaha',
                model: 'MT07',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Yamaha',
                model: 'MT09',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Yamaha',
                model: 'MT10',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
            new Motorbike({
                brand : 'Yamaha',
                model: 'Niken',
                engine: '',
                capacity: 2,
                warranty: 3,
                taxes: 25,
                gearbox: 'Auto',
                fuelType: 'Disesl',
                FuelCapacity: 18,
                price: 1000,
            }),
        ]))
    }
}